name: CI

on: [push, pull_request]

jobs:
  vagrantfile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Check Vagrant version
        run: vagrant --version

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: [2.3, 2.4, 2.5, 2.6, 2.7, 3.0]
    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests with Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
        run: bundle exec rake
