name: CI

on: [push, pull_request]

jobs:
  vagrantfile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Vagrant version
        run: vagrant --version

      - name: Vagrant up
        run: vagrant up

      - name: Vagrant output - Docker
        run: vagrant ssh -c "docker --version"

      - name: Vagrant output - Docker compose
        run: vagrant ssh -c "docker-compose --version"

      - name: Vagrant output - Ruby
        run: vagrant ssh -c "ruby --version"

      - name: Vagrant output - Bundler
        run: vagrant ssh -c "bundler --version"

      - name: Vagrant output - Linux-only tests
        run: vagrant ssh -c "cd /vagrant/ && RUNNER_OS=Linux bundle exec rake"
