name: CI

on: [push, pull_request]

jobs:
  vagrantfile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Vagrant version
        run: vagrant --version

      - name: Vagrant up
        run: vagrant up

      - name: Test Vagrant ouput
        run: vagrant ssh -c "echo 'hello world!'"
