name: CI

on: [push, pull_request]

jobs:
  vagrantfile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Check Vagrant version
        run: vagrant --version
