name: CI

on: [push, pull_request]

jobs:
  vagrantfile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Vagrant cache of box
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Vagrant version
        run: vagrant --version

      - name: Vagrant up
        run: vagrant up

      - name: Vagrant ouput - Docker
        run: vagrant ssh -c "docker --version"

      - name: Vagrant ouput - Docker compose
        run: vagrant ssh -c "docker-compose --version"

      - name: Vagrant ouput - Ruby
        run: vagrant ssh -c "ruby --version"

      - name: Vagrant ouput - Bundler
        run: vagrant ssh -c "bundler --version"
